#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/clips_manually_uploaded.ipynb
import os, json, csv
import sqlite3
import requests, argparse
from datetime import datetime
from panoptes_client import Project, Panoptes
from db_setup import *
from zooniverse_setup import *


def main():
    "Handles argument parsing and launches the correct function."
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--user", "-u", help="Zooniverse username", type=str, required=True
    )
    parser.add_argument(
        "--password", "-p", help="Zooniverse password", type=str, required=True
    )
    parser.add_argument(
        "-db",
        "--db_path",
        type=str,
        help="the absolute path to the database file",
        default=r"koster_lab.db",
        required=True,
    )

    args = parser.parse_args()

    project = auth_session(args.user, args.password)

    # Specify the last and first dates when subjects were manually uploaded
    last_date = "2020-01-10 00:00:00 UTC"
    first_date = "2019-11-17 00:00:00 UTC"

    # get the export subjects
    export = project.get_export("subjects")

    # save the response as pandas data frame
    rawdata = pd.read_csv(
        io.StringIO(export.content.decode("utf-8")),
        usecols=["subject_id", "metadata", "created_at"],
    )

    # Filter manually uploaded subjects
    man_data = rawdata[
        (last_date >= rawdata.created_at) & (first_date <= rawdata.created_at)
    ]

    # filter clip subjects
    man_data = man_data[man_data["metadata"].str.contains(".mp4")].reset_index()

    # Specify the location to write the csv files
    dstn_subj = "../all_subjects.csv"
    out_location_subj = "../manually_uploaded_subjects.csv"

    # flatten the metadata information
    flat_metadata = pd.json_normalize(man_data.metadata.apply(json.loads))

    # Select the filename of the clips
    clip_filenames = flat_metadata["filename"]

    # Get the starting time of clips in relation to the original movie
    # split the filename, select the last section, and remove the extension type
    flat_metadata["start_time"] = (
        clip_filenames.str.rsplit("_", 1).str[-1].str.replace(".mp4", "")
    )

    # Extract the filename of the original movie
    flat_metadata["movie_filename"] = flat_metadata.apply(
        lambda x: x["filename"].replace("_" + x["start_time"], ""), axis=1
    )

    # Get the end time of clips in relation to the original movie
    flat_metadata["start_time"] = pd.to_numeric(
        flat_metadata["start_time"], downcast="signed"
    )
    flat_metadata["end_time"] = flat_metadata["start_time"] + 10

    # select only relevant columns
    flat_metadata = flat_metadata[
        ["filename", "movie_filename", "start_time", "end_time"]
    ]

    # Retrieve the id and filename from the movies table
    flat_metadata["movie_id"] = flat_metadata.apply(
        lambda x: execute_query(
            f"SELECT movie_id FROM movies WHERE filename=={x['movie_filename']}"
        )
    )

    # add movie_id to the flat metadata
    # clip_metadata = pd.merge(flat_metadata, movies, how = 'left',
    #                         left_on='movie_filename', right_on='filename')

    # Drop metadata column and define clip creation date as time uploaded to Zooniverse
    man_data = man_data.drop(columns="metadata")

    # Combine the information
    comb_data = pd.concat(man_data, flat_metadata, axis=1)

    # Select information to include in the clips table
    clips = comb_data.drop(columns="subject_id").rename(
        columns={"created_at": "clipped_date", "index": "id"}
    )

    # Combine the info to include in the subjects table
    subjects = comb_data.rename(
        columns={
            "created_at": "zoo_upload_date",
            "index": "clip_id",
            "subject_id": "id",
        }
    )

    # update the tables
    conn = create_connection(args.db_path)

    try:
        insert_many(conn, [tuple(i) for i in clips.values], "clips", 6)
        insert_many(conn, [tuple(i) for i in subjects.values], "subjects", 9)
    except sqlite3.Error as e:
        print(e)

    conn.commit()


if __name__ == "__main__":
    main()
